### ISSUE TITLE
Test build on Windows

### ISSUE THREAD

**Issue by SommerEngineering** [SommerEngineering/QuantumRandom#1]
The build under Windows must be tested. Probably, the path must be adjusted. Linux and macOS use now `/usr/local/lib` as static location as mentioned by the HU Berlin. Is there a static location for Windows?

**Comment by SommerEngineering** [comment]
If this issue is done, please update the README.md

**Comment by SommerEngineering** [comment]
https://wiki.dlang.org/Compiling_and_linking_with_DMD_on_Windows

**Comment by DiddiZ** [comment]
Besides `winsxs` or `system32` there is no shared location for Windows that I'd know of. Adding libaries there would likely require an installer. Therefore static libraries usually are placed in the project folder.

**Comment by DiddiZ** [comment]
Building on Windows work again.
